/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
static yyconst short int yy_accept[367] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   58,   48,
       56,   52,    1,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   46,   55,   51,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   55,   55,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   47,
       54,   49,   47,   47,   47,   47,   47,   47,   47,   47,
       54,   54,   47,   47,   47,   47,   47,   47,   47,   37,
       53,   50,    2,   37,   37,   37,   37,   37,   37,   37,
       48,   56,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   46,   55,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,    0,    0,   44,
       55,   55,   55,   44,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   47,   54,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,    0,    0,
       45,   54,   54,   54,   45,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   37,   36,   35,   53,   37,   37,
       37,   37,   37,   37,   37,   48,   48,   48,   48,   48,
       48,   48,   30,   48,   48,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   16,   46,   46,   44,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   16,   46,   46,

       47,   47,   47,   47,   47,   47,   23,   47,   47,   45,
       47,   47,   47,   47,   47,   47,   23,   47,   47,   37,
       37,   37,   37,   37,    6,   37,   48,   48,   48,   48,
       27,   26,   48,   28,   29,   46,   46,    0,   46,   46,
       46,   13,   12,   46,   14,   15,   46,   46,    0,   46,
       46,   46,   13,   12,   46,   14,   15,    0,   47,   47,
       20,   19,   47,   21,   22,    0,   47,   47,   20,   19,
       47,   21,   22,   37,   37,    8,   37,   37,    7,   48,
       48,   48,   48,   48,   46,   46,    0,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,    0,   47,   47,

       47,   47,   47,   47,    9,   37,   37,    5,   48,   48,
       24,   48,   25,   46,   46,    0,   34,   10,   46,   11,
       46,   46,   34,   10,   46,   11,    0,   33,   17,   18,
       33,   17,   18,    3,    4,   48,   48,   41,   46,   46,
        0,   38,   46,   46,   38,    0,   48,   40,   46,   43,
        0,   46,   43,    0,   48,   46,   32,   46,   31,   48,
       46,   46,   39,   42,   42,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    1,    1,    7,    8,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,    1,    1,
        1,    1,    1,    1,   10,    1,   11,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
        1,   13,   14,   15,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,    1,    1,   25,   26,   27,
       28,    1,    1,   29,   30,   31,   32,    1,   33,    1,
       34,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    2,    3,    2,    4,    1,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[378] =
    {   0,
        0,    0,   34,   68,  101,  127,  153,  177,  915,    0,
      105,  916,  916,  898,  893,  881,  888,  876,  886,  880,
      880,  878,  873,    0,  109,  916,  888,  883,   86,  879,
      867,  877,  871,  871,  869,  864,  131,  120,  158,  201,
      208,  227,  162,  116,  199,  212,  180,  213,  194,    0,
      169,  916,  175,  861,  871,  865,  865,  863,  858,  246,
      185,  253,  260,  218,  246,  251,  254,  266,  268,  136,
      119,  916,  142,  214,  289,  239,  162,  296,  298,  300,
        0,  306,  860,  857,  858,  857,  854,  868,  851,  851,
      854,  855,    0,  307,  850,  847,  857,  849,  846,  845,

      842,  856,  839,  839,  842,  843,  252,  285,  314,  295,
      325,  329,  336,  337,  322,  328,  330,  336,  342,  345,
      344,  361,  358,  360,  373,  363,    0,  394,  845,  837,
      831,  824,  835,  818,  815,  814,  812,  375,  401,  406,
      387,  413,  417,  424,  425,  392,  410,  415,  416,  429,
      430,  428,  443,  444,  317,  328,  351,  159,  449,  451,
      465,  470,  472,  475,  477,  820,  786,  793,  788,  795,
      785,  796,    0,  788,  784,  791,  774,  801,  781,  761,
      755,  757,  735,  732,    0,  718,  703,  916,  470,  467,
      485,  490,  487,  495,  493,  505,  511,  513,  519,  527,

      699,  682,  655,  651,  636,  646,    0,  635,  629,  916,
      536,  535,  537,  545,  550,  558,  553,  563,  566,  436,
      539,  542,  486,  586,  565,  589,  614,  605,  605,  589,
        0,    0,  591,    0,    0,  583,  569,  578,  560,  537,
      521,    0,    0,  513,    0,    0,  579,  584,  610,  597,
      599,  605,  611,  613,  621,  619,  627,  522,  510,  500,
        0,    0,  497,    0,    0,  651,  636,  642,  644,  650,
      652,  658,  660,  594,  600,  642,  679,  681,  686,  500,
      485,  475,  465,  468,  465,  446,  426,  429,  400,  383,
      382,  670,  675,  687,  693,  690,  685,  361,  370,  350,

      350,  699,  705,  702,  691,  725,  728,  731,  324,  319,
        0,  338,    0,  299,  287,  282,    0,    0,  292,    0,
      719,  721,  722,  734,  735,  736,  268,    0,    0,    0,
      737,  749,  750,  756,  765,  245,  254,    0,  239,  247,
      199,    0,  755,  767,  758,  196,  184,    0,  168,    0,
      175,  764,  770,  166,  128,  123,  916,  772,  916,  128,
      123,  788,    0,    0,  780,  916,  819,  824,  829,  113,
      834,  838,  843,  848,  852,  857,  862
    } ;

static yyconst short int yy_def[378] =
    {   0,
      366,    1,  366,  366,  367,  368,  369,  369,  366,  370,
      366,  366,  366,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  371,  366,  366,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  372,  373,  373,  372,
      372,  372,   42,   42,   42,   42,   42,   42,   42,  374,
      366,  366,  374,  374,  374,  374,  374,  374,  374,  375,
      376,  376,  375,   63,   63,   63,   63,   63,   63,  377,
      366,  366,  377,  377,  377,  377,  377,  377,  377,  377,
      370,  366,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  371,  366,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,   42,  366,  373,   42,
      373,  373,  366,  373,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,  374,  366,  374,  374,
      374,  374,  374,  374,  374,  374,  374,   63,  366,  376,
       63,  376,  376,  366,  376,   63,   63,   63,   63,   63,
       63,   63,   63,   63,  377,  377,  377,  366,  377,  377,
      377,  377,  377,  377,  377,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  366,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  366,
       63,   63,   63,   63,   63,   63,   63,   63,   63,  377,
      377,  377,  377,  377,  377,  377,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  371,  371,  366,  371,  371,
      371,  371,  371,  371,  371,  371,   42,   42,  366,   42,
       42,   42,   42,   42,   42,   42,   42,  366,  374,  374,
      374,  374,  374,  374,  374,  366,   63,   63,   63,   63,
       63,   63,   63,  377,  377,  377,  377,  377,  377,  370,
      370,  370,  370,  370,  371,  371,  366,  371,  371,  371,
      371,   42,   42,   42,   42,   42,   42,  366,  374,  374,

      374,   63,   63,   63,  377,  377,  377,  377,  370,  370,
      370,  370,  370,  371,  371,  366,  371,  371,  371,  371,
       42,   42,   42,   42,   42,   42,  366,  374,  374,  374,
       63,   63,   63,  377,  377,  370,  370,  370,  371,  371,
      366,  371,   42,   42,   42,  366,  370,  370,  371,  371,
      366,   42,   42,  366,  370,  371,  366,   42,  366,  370,
      371,   42,  370,  371,   42,    0,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366
    } ;

static yyconst short int yy_nxt[951] =
    {   0,
       10,   11,   12,   11,   13,   10,   11,   10,   10,   10,
       10,   14,   15,   16,   17,   10,   18,   19,   20,   10,
       10,   10,   10,   21,   22,   10,   23,   10,   10,   10,
       10,   10,   10,   10,   24,   25,   26,   25,   24,   24,
       25,   24,   24,   24,   24,   27,   28,   29,   30,   24,
       31,   32,   33,   24,   24,   24,   24,   34,   35,   24,
       36,   24,   24,   24,   24,   24,   24,   24,   37,   38,
       26,   38,   37,   37,   39,   37,   37,   37,   37,   40,
       41,   42,   43,   37,   44,   45,   46,   37,   37,   37,
       37,   47,   48,   37,   49,   37,   37,   37,   37,   37,

       37,   37,   51,   52,   51,   97,   82,   51,   82,   98,
       94,   82,   94,   81,   53,   94,   99,   54,   55,   56,
      158,  111,  158,  111,   57,   58,  112,   59,   61,   52,
       61,  364,  108,   62,  108,  107,  363,  109,  110,  107,
       63,  156,  157,   64,   65,   66,  107,  156,  157,  121,
       67,   68,  361,   69,   71,   72,   71,  360,   73,  113,
      158,  113,  158,   74,  112,  114,   75,  156,  157,   76,
      128,   77,  128,   78,  359,  128,   79,   80,   71,   72,
       71,  107,   73,  357,  120,  107,  142,   74,  142,  162,
       75,  143,  107,   76,  129,   77,  356,   78,  130,  107,

       79,   80,  108,  107,  108,  131,  124,  109,  110,  108,
      107,  108,  355,  107,  109,  110,  115,  107,  107,  156,
      157,  122,  107,  354,  107,  126,  351,  116,  108,  107,
      108,  107,  107,  109,  110,  107,  107,  138,  159,  123,
      125,  138,  107,  107,  156,  157,  117,  139,  138,  139,
      118,  149,  140,  141,  144,  350,  144,  119,  349,  143,
      145,  139,  348,  139,  347,  138,  140,  141,  150,  138,
      138,  107,  161,  138,  138,  107,  138,  138,  151,  146,
      152,  138,  107,  147,  138,  138,  108,  138,  108,  138,
      148,  138,  188,  153,  156,  157,  138,  346,  138,  154,

      342,  156,  157,  156,  157,  156,  157,   82,   94,   82,
       94,  341,   82,   94,  107,  108,  340,  108,  107,  160,
      163,  114,  156,  157,  164,  107,  111,  165,  111,  339,
      113,  112,  113,  156,  157,  112,  114,  113,  108,  113,
      108,  107,   94,  188,  114,  107,  338,  107,  337,  191,
      189,  107,  107,  107,  336,  107,  156,  157,  190,  107,
      107,  107,  192,  107,  107,  107,  107,  107,  107,  330,
      193,  329,  107,  194,  195,  107,  196,  107,  328,  107,
      107,  107,  107,  107,  107,  327,  107,  200,  107,  197,
      198,  107,  107,  107,  138,  128,  107,  128,  138,  199,

      128,  320,  139,  107,  139,  138,  138,  139,  210,  139,
      138,  211,  319,  145,  142,  138,  142,  138,  144,  143,
      144,  318,  138,  143,  145,  144,  139,  144,  139,  138,
      128,  210,  145,  138,  138,  138,  212,  317,  138,  138,
      138,  156,  157,  213,  215,  138,  214,  138,  138,  138,
      316,  138,  138,  138,  156,  157,  156,  157,  217,  138,
      138,  216,  138,  138,  220,  274,  138,  138,  219,  218,
      156,  157,  315,  138,  138,  156,  157,  156,  157,  221,
      156,  157,  156,  157,  314,  247,  107,  313,  249,  107,
      107,  156,  157,  107,  312,  222,  311,  107,  248,  224,

      107,  223,  277,  226,  107,  225,  107,  250,  107,  107,
      251,  310,  253,  107,  107,  107,  107,  107,  107,  309,
      107,  301,  252,  107,  107,  107,  300,  255,  107,  299,
      107,  298,  107,  254,  107,  107,  107,  291,  107,  266,
      256,  107,  107,  107,  156,  157,  107,  156,  157,  107,
      107,  257,  267,  290,  138,  138,  138,  107,  138,  138,
      268,  276,  275,  289,  269,  138,  138,  138,  138,  138,
      156,  157,  138,  138,  271,  138,  138,  138,  270,  288,
      138,  138,  138,  138,  272,  138,  138,  287,  138,  138,
      273,  156,  157,  138,  156,  157,  138,  286,  107,  156,

      157,  278,  107,  107,  292,  156,  157,  107,  285,  107,
      279,  108,  293,  108,  107,  284,  294,  188,  107,  287,
      107,  283,  107,  305,  107,  295,  306,  107,  107,  107,
      107,  282,  107,  281,  107,  107,  107,  296,  107,  280,
      107,  107,  107,  107,  107,  297,  107,  156,  157,  107,
      107,  107,  139,  265,  139,  302,  264,  107,  210,  138,
      298,  138,  263,  138,  262,  138,  138,  138,  303,  138,
      261,  138,  138,  138,  138,  138,  304,  138,  260,  138,
      138,  138,  138,  138,  156,  157,  156,  157,  138,  321,
      138,  156,  157,  107,  107,  323,  156,  157,  107,  259,

      107,  322,  258,  307,  326,  107,  107,  331,  107,  107,
      107,  308,  107,  107,  324,  107,  107,  107,  138,  325,
      107,  333,  138,  107,  138,  138,  332,  246,  138,  138,
      156,  157,  138,  156,  157,  138,  156,  157,  107,  245,
      107,  107,  107,  345,  107,  107,  334,  335,  244,  343,
      344,  107,  107,  107,  107,  107,  138,  107,  107,  107,
      138,  156,  157,  243,  107,  107,  107,  138,  138,  138,
      156,  157,  138,  138,  352,  353,  242,  107,  107,  138,
      138,  107,  241,  107,  240,  107,  107,  107,  107,  107,
      107,  107,  358,  107,  107,  107,  365,  107,  239,  107,

      107,  362,  107,  107,  238,  237,  236,  107,  235,  234,
      107,  107,  233,  232,  231,  230,  229,  228,  107,   50,
       50,   50,   50,   50,   60,   60,   60,   60,   60,   70,
       70,   70,   70,   70,   93,  227,  209,   93,  107,  107,
      208,  107,  107,  109,  109,  207,  109,  109,  127,  206,
      205,  127,  138,  138,  204,  138,  138,  140,  140,  203,
      140,  140,  155,  202,  201,  155,  155,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  137,
      136,  135,  134,  133,  132,  106,  105,  104,  103,  102,

      101,  100,   96,   95,   92,   91,   90,   89,   88,   87,
       86,   85,   84,   83,  366,    9,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366
    } ;

static yyconst short int yy_chk[951] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    5,    5,    5,   29,   11,    5,   11,   29,
       25,   11,   25,  370,    5,   25,   29,    5,    5,    5,
       71,   38,   71,   38,    5,    5,   38,    5,    6,    6,
        6,  361,   37,    6,   37,   44,  360,   37,   37,   44,
        6,   70,   70,    6,    6,    6,   44,   73,   73,   44,
        6,    6,  356,    6,    7,    7,    7,  355,    7,   39,
      158,   39,  158,    7,   39,   39,    7,   77,   77,    7,
       51,    7,   51,    7,  354,   51,    7,    7,    8,    8,
        8,   43,    8,  351,   43,   43,   61,    8,   61,   77,
        8,   61,   43,    8,   53,    8,  349,    8,   53,   47,

        8,    8,   40,   47,   40,   53,   47,   40,   40,   41,
       47,   41,  347,   49,   41,   41,   40,   49,   45,   74,
       74,   45,   45,  346,   49,   49,  341,   41,   42,   45,
       42,   46,   48,   42,   42,   46,   48,   64,   74,   46,
       48,   64,   46,   48,   76,   76,   42,   60,   64,   60,
       42,   64,   60,   60,   62,  340,   62,   42,  339,   62,
       62,   63,  337,   63,  336,   65,   63,   63,   65,   65,
       66,  107,   76,   67,   66,  107,   65,   67,   66,   63,
       67,   66,  107,   63,   67,   68,  108,   69,  108,   68,
       63,   69,  108,   68,   75,   75,   68,  327,   69,   69,

      319,   78,   78,   79,   79,   80,   80,   82,   94,   82,
       94,  316,   82,   94,  110,  109,  315,  109,  110,   75,
       78,  109,  155,  155,   79,  110,  111,   80,  111,  314,
      112,  111,  112,  156,  156,  112,  112,  113,  114,  113,
      114,  115,  113,  113,  114,  115,  312,  116,  310,  117,
      115,  116,  115,  117,  309,  118,  157,  157,  116,  118,
      117,  119,  118,  121,  120,  119,  118,  121,  120,  301,
      119,  300,  119,  120,  121,  120,  122,  123,  299,  124,
      122,  123,  126,  124,  122,  298,  126,  126,  123,  123,
      124,  122,  125,  126,  138,  128,  125,  128,  138,  125,

      128,  291,  139,  125,  139,  138,  141,  140,  139,  140,
      141,  146,  290,  140,  142,  146,  142,  141,  143,  142,
      143,  289,  146,  143,  143,  144,  145,  144,  145,  147,
      144,  144,  145,  147,  148,  149,  147,  288,  148,  149,
      147,  220,  220,  148,  150,  148,  149,  152,  150,  151,
      287,  152,  150,  151,  159,  159,  160,  160,  152,  150,
      151,  151,  153,  154,  159,  220,  153,  154,  154,  153,
      161,  161,  286,  153,  154,  162,  162,  163,  163,  160,
      164,  164,  165,  165,  285,  189,  190,  284,  191,  189,
      190,  223,  223,  189,  283,  161,  282,  190,  190,  163,

      189,  162,  223,  165,  191,  164,  193,  192,  191,  192,
      193,  281,  195,  192,  194,  191,  195,  193,  194,  280,
      192,  263,  194,  195,  196,  194,  260,  197,  196,  259,
      197,  258,  198,  196,  197,  196,  198,  244,  199,  211,
      199,  197,  199,  198,  221,  221,  200,  222,  222,  199,
      200,  200,  212,  241,  212,  211,  213,  200,  212,  211,
      213,  222,  221,  240,  214,  212,  211,  213,  214,  215,
      225,  225,  217,  215,  216,  214,  217,  216,  215,  239,
      215,  216,  218,  217,  218,  219,  218,  238,  216,  219,
      219,  224,  224,  218,  226,  226,  219,  237,  247,  274,

      274,  224,  247,  248,  247,  275,  275,  248,  236,  247,
      226,  249,  248,  249,  248,  233,  250,  249,  251,  249,
      250,  230,  251,  274,  252,  251,  275,  250,  252,  251,
      253,  229,  254,  228,  253,  252,  254,  252,  256,  227,
      255,  253,  256,  254,  255,  255,  257,  276,  276,  256,
      257,  255,  266,  209,  266,  267,  208,  257,  266,  267,
      266,  268,  206,  269,  205,  268,  267,  269,  268,  270,
      204,  271,  268,  270,  269,  271,  271,  272,  203,  273,
      270,  272,  271,  273,  277,  277,  278,  278,  272,  292,
      273,  279,  279,  292,  293,  294,  305,  305,  293,  202,

      292,  293,  201,  277,  297,  293,  294,  302,  297,  296,
      294,  278,  295,  296,  295,  297,  295,  294,  302,  296,
      296,  304,  302,  295,  303,  304,  303,  187,  303,  302,
      306,  306,  304,  307,  307,  303,  308,  308,  321,  186,
      322,  323,  321,  325,  322,  323,  306,  307,  184,  321,
      322,  322,  323,  324,  325,  326,  331,  324,  325,  326,
      331,  334,  334,  183,  324,  325,  326,  331,  332,  333,
      335,  335,  332,  333,  343,  344,  182,  345,  343,  332,
      333,  345,  181,  352,  180,  343,  344,  352,  345,  353,
      344,  358,  352,  353,  352,  358,  362,  344,  179,  365,

      353,  358,  358,  365,  178,  177,  176,  362,  175,  174,
      365,  362,  172,  171,  170,  169,  168,  167,  362,  367,
      367,  367,  367,  367,  368,  368,  368,  368,  368,  369,
      369,  369,  369,  369,  371,  166,  137,  371,  372,  372,
      136,  372,  372,  373,  373,  135,  373,  373,  374,  134,
      133,  374,  375,  375,  132,  375,  375,  376,  376,  131,
      376,  376,  377,  130,  129,  377,  377,  106,  105,  104,
      103,  102,  101,  100,   99,   98,   97,   96,   95,   92,
       91,   90,   89,   88,   87,   86,   85,   84,   83,   59,
       58,   57,   56,   55,   54,   36,   35,   34,   33,   32,

       31,   30,   28,   27,   23,   22,   21,   20,   19,   18,
       17,   16,   15,   14,    9,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tipswnd.lex"
#define INITIAL 0
/*
 *
gcc -D DLL -shared -o ../plugin/vjde/tipswnd.dll tipswnd.c -luser32 -lcomctl32 -lgdi32 -mwindows
 */
#line 6 "tipswnd.lex"
#include <windows.h>
#ifdef DLL
#define _DL_EXPORT __declspec(dllexport) extern
#else
#define _DL_EXPORT
#include "data.h"
#endif

#define YY_INPUT(buf,result,max_size)  {\
    result = GetNextChar(buf, max_size); \
    if (  result <= 0  ) \
      result = YY_NULL; \
    }
	
int GetNextChar(char* buf,int max_size);
char cBuffer[2048];
int bufferSize;
int offset;
int iLineCount;
int top ;
int left;
int iMaxWidth;
int iMaxHeight;
BOOL stoped ;

HWND hwndText; // Vim 输入窗口
HWND m_vimHwnd; // vim 窗口
HDC hdc;
int paintX=2;
int paintY=0;
SIZE sizeXY; 
int paramSkip;
int currentLine;
void ColoredText(int r , int g, int b ,char *p , int l) ;
void MyTextOut(char *p , int l) ;
#define MYLIST 1

#define MYLISTEX 2

#define PARAMETER 3

#line 737 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 46 "tipswnd.lex"

#line 893 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 367 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 916 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "tipswnd.lex"
{
MyTextOut(yytext,1);
if (paramSkip==0) {
	BEGIN PARAMETER;
}
paramSkip=1;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 54 "tipswnd.lex"
{
MyTextOut(yytext,1);
BEGIN 0;
}
	YY_BREAK
case 3:
#line 59 "tipswnd.lex"
case 4:
#line 60 "tipswnd.lex"
case 5:
#line 61 "tipswnd.lex"
case 6:
#line 62 "tipswnd.lex"
case 7:
#line 63 "tipswnd.lex"
case 8:
#line 64 "tipswnd.lex"
case 9:
#line 65 "tipswnd.lex"
case 10:
#line 66 "tipswnd.lex"
case 11:
#line 67 "tipswnd.lex"
case 12:
#line 68 "tipswnd.lex"
case 13:
#line 69 "tipswnd.lex"
case 14:
#line 70 "tipswnd.lex"
case 15:
#line 71 "tipswnd.lex"
case 16:
#line 72 "tipswnd.lex"
case 17:
#line 73 "tipswnd.lex"
case 18:
#line 74 "tipswnd.lex"
case 19:
#line 75 "tipswnd.lex"
case 20:
#line 76 "tipswnd.lex"
case 21:
#line 77 "tipswnd.lex"
case 22:
#line 78 "tipswnd.lex"
case 23:
#line 79 "tipswnd.lex"
case 24:
#line 80 "tipswnd.lex"
case 25:
#line 81 "tipswnd.lex"
case 26:
#line 82 "tipswnd.lex"
case 27:
#line 83 "tipswnd.lex"
case 28:
#line 84 "tipswnd.lex"
case 29:
#line 85 "tipswnd.lex"
case 30:
YY_RULE_SETUP
#line 85 "tipswnd.lex"
{
	ColoredText(0x00,0x00,0xff,yytext,strlen(yytext));
}
	YY_BREAK
case 31:
#line 89 "tipswnd.lex"
case 32:
#line 90 "tipswnd.lex"
case 33:
#line 91 "tipswnd.lex"
case 34:
YY_RULE_SETUP
#line 91 "tipswnd.lex"
{
	ColoredText(0xff,0,0xff,yytext,strlen(yytext));
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "tipswnd.lex"
{
	ColoredText(0xff,0x00,0x00,yytext,strlen(yytext)-1);
	MyTextOut(",",1);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "tipswnd.lex"
{
	ColoredText(0xff,0x00,0x00,yytext,strlen(yytext)-1);
	MyTextOut(")",1);
	BEGIN 0;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "tipswnd.lex"
{
	MyTextOut(yytext,strlen(yytext));
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 "tipswnd.lex"
{
	ColoredText(0xff,0x00,0xff,yytext,strlen(yytext));
	BEGIN MYLISTEX;
}
	YY_BREAK
case 39:
#line 111 "tipswnd.lex"
case 40:
#line 112 "tipswnd.lex"
case 41:
#line 113 "tipswnd.lex"
case 42:
#line 114 "tipswnd.lex"
case 43:
YY_RULE_SETUP
#line 114 "tipswnd.lex"
{
	ColoredText(0xff,0,0xff,yytext,strlen(yytext));
	BEGIN MYLIST;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "tipswnd.lex"
{
	ColoredText(0xff,0x00,0x00,yytext,strlen(yytext)-1);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 121 "tipswnd.lex"
{
	ColoredText(0xbb,0x00,0x00,yytext,strlen(yytext)-1);
}
	YY_BREAK
case 46:
#line 126 "tipswnd.lex"
case 47:
#line 127 "tipswnd.lex"
case 48:
YY_RULE_SETUP
#line 127 "tipswnd.lex"
{
	MyTextOut(yytext,strlen(yytext));
}
	YY_BREAK
case 49:
#line 131 "tipswnd.lex"
case 50:
#line 132 "tipswnd.lex"
case 51:
#line 133 "tipswnd.lex"
case 52:
YY_RULE_SETUP
#line 133 "tipswnd.lex"
{ 
++currentLine;
paintX=2;
paintY= currentLine*iMaxHeight+2; 
}
	YY_BREAK
case 53:
#line 139 "tipswnd.lex"
case 54:
#line 140 "tipswnd.lex"
case 55:
#line 141 "tipswnd.lex"
case 56:
YY_RULE_SETUP
#line 141 "tipswnd.lex"
{
	//TextOut(hdc,paintX,paintY,yytext,strlen(yytext));
	GetTextExtentPoint(hdc,yytext,strlen(yytext),&sizeXY);
	paintX += sizeXY.cx;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "tipswnd.lex"
ECHO;
	YY_BREAK
#line 1178 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MYLIST):
case YY_STATE_EOF(MYLISTEX):
case YY_STATE_EOF(PARAMETER):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 367 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 367 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 366);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 146 "tipswnd.lex"


void MyTextOut(char *p,int l) {
	TextOut(hdc,paintX,paintY,p,l);
	GetTextExtentPoint(hdc,p,l,&sizeXY);
	paintX += sizeXY.cx;
}
void ColoredText(int r , int g, int b ,char *p , int l) {
	SetTextColor(hdc, RGB(r,g,b)); //设置文字颜色
	TextOut(hdc,paintX,paintY,p,l);
	GetTextExtentPoint(hdc,p,l,&sizeXY);
	paintX += sizeXY.cx;
	SetTextColor(hdc, RGB(0x0,0,0x0)); //设置文字颜色
}
int GetNextChar(char* buf,int max_size) {
	if ( offset>=bufferSize) {
		return 0;
	}
	int len = bufferSize-offset-1;
	len = max_size>len?len:max_size;
	memcpy(buf,cBuffer,len);
	offset += len;
	return len;
}
int yywrap()
{
	return 1;
}
BOOL CALLBACK EnumWndProc(HWND hWnd,LPARAM lParam)
{
	HWND* lhwnd=(HWND*)lParam;
	char buf[50];
	GetClassName(hWnd,buf,50);
	//VimTextArea is the class name of main editing window of VIM
	if (strcmp(buf,"VimTextArea") == 0)
	{
		*lhwnd=hWnd; 
		return FALSE;
	}
	return TRUE;
}
void FindVimWindow()
{
	HWND hTempHwnd = GetForegroundWindow();
	if(hTempHwnd)
	{
		m_vimHwnd = hTempHwnd;
	}
	else
	{
		//but getting VIM window failed get the Desktop window. This is used to get the 
		//VIM rectangle. So even desktop window is also OK.
		m_vimHwnd = GetDesktopWindow();
	}

	//Get the editing window in the VIM.
	EnumChildWindows(m_vimHwnd,EnumWndProc,(LPARAM)&hwndText);

	//GetWindowRect(hwndText,vimRect);
}
void PaintText(HDC hdc) 
{
paintX=2;
paintY=2;
currentLine = 0;
offset= 0;
paramSkip=0;
yylex();
}
BOOL RetriveTextSize(HDC hdc)
{
	SIZE size ;

	iLineCount = 0;
	iMaxWidth = 0;
	iMaxHeight = 0;

	char *p = cBuffer;
	char *temp = cBuffer;
	while ( *temp != '\0') {
		if (*temp == '\n') {
			iLineCount++;
			 GetTextExtentPoint(hdc,p,temp-p-1,&size);
		   	 {
			iMaxWidth = size.cx > iMaxWidth ? size.cx:iMaxWidth;
			iMaxHeight = size.cy > iMaxHeight ? size.cy:iMaxHeight;
			}
			p = temp+1;
		}
		++temp;
	}
	if ( p < temp ) 
	{ //最后未包含一个\n
		iLineCount++;
		 GetTextExtentPoint(hdc,p,temp-p-1,&size); 
		 {
			iMaxWidth = size.cx > iMaxWidth ? size.cx:iMaxWidth;
			iMaxHeight = size.cy > iMaxHeight ? size.cy:iMaxHeight;
		}
	}
}
int ReadInt(char *in,int l)
{
	char buffer[64];
	snprintf(buffer,l,"%s",in);
	return atoi(buffer);
}
int AdjustPosEx(LPRECT rect, int w,int h)
{
	if ( left+w+10 > rect->right ) {
		if ( left > w+10 ) {
			left = left - w - 10;
		}
		else {
			left = rect->right - w - 20;
		}
	}
	if ( top + h + 10 > rect->bottom ) {
		if ( top > h + 10 ) {
			top = top - h - 20;
		}
		else {
			top = rect->bottom - h - 20;
		}
	}
}
/**
 * Caculate the left-top point of tips window.
 * @param in "8;12;30;80;\n.."
 *            line;col; line total;colums total;
 */
int AdjustPos(LPRECT rect,char *in)
{
	int t,l,w,h;
	char *p = in;
	char *temp = in;
	char buffer[128];

	while ( *temp!=';') ++temp;
	t = ReadInt(p,temp-p);
	++temp;
	p = temp;

	while ( *temp!=';' ) ++temp;
	l = ReadInt(p,temp-p);
	++temp;
	p = temp;

	while ( *temp!=';' ) ++temp;
	h = ReadInt(p,temp-p);
	++temp;
	p = temp;

	while ( *temp!=';' ) ++temp;
	w = ReadInt(p,temp-p);
	++temp;
	++temp; // skip a \n

	top = (rect->bottom-rect->top)*t/h + rect->top;
	left = (rect->right-rect->left)*l/w + rect->left;
	return temp - in;

	//snprintf(buffer,64,p,
}
//一、消息处理函数
//参数:窗口句柄，消息，消息参数，消息参数
LRESULT CALLBACK WndProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
{
	//处理感兴趣的消息
	switch (message)
	{
		case WM_KEYDOWN:
			switch (wParam)
			{
				stoped = TRUE;
				DestroyWindow(hwnd);
				return 0;
			}
		case WM_LBUTTONDOWN:
		case WM_RBUTTONDOWN://鼠标消息
			{
				stoped = TRUE;
				DestroyWindow(hwnd);
				return 0;
			}
		case WM_PAINT:
			{
				char hello[]="你好，我是EasyWin !";
				char buff[128];
				//HDC hdc;
				PAINTSTRUCT ps;
				RECT rect;
				HFONT font;
				HGDIOBJ oldFont;


			    font	= CreateFont(12, 0, 0, 0, FW_REGULAR, 0, 0, 0, 0, 0, 0, 0, 0, "MS Sans Serif");

				hdc=BeginPaint( hwnd,&ps ); //取得设备环境句柄

				oldFont = SelectObject(hdc,font);
				RetriveTextSize(hdc);

				GetWindowRect( GetDesktopWindow() , &rect);
				AdjustPosEx(&rect,iMaxWidth+20,iMaxHeight * iLineCount + 20);
				MoveWindow(hwnd,left,top, iMaxWidth+20,(iMaxHeight * iLineCount)+20,TRUE);


				GetClientRect(hwnd,&rect);
				InflateRect(&rect,-1,-1);
				FillRect(hdc, &rect,CreateSolidBrush(RGB(0xff,0xff,0x99)));
				//FillRect(hdc, &rect,CreateSolidBrush(RGB(0x00,0x00,0xff)));

				SelectObject(hdc,CreatePen(PS_SOLID,2,RGB(162,162,162)));

				SetBkMode(hdc,TRANSPARENT);
				SetTextColor(hdc, RGB(0,0,0)); //设置文字颜色

				oldFont = SelectObject(hdc,font);
				PaintText(hdc);

				SelectObject(hdc,oldFont);
				EndPaint( hwnd, &ps ); //释放资源
				break;
			}
		case WM_CLOSE:
			break;
		case WM_DESTROY:
			//PostQuitMessage(0);
			//当用户关闭窗口，窗口销毁，程序需结束，发退出消息，以退出消息循环
			return 0 ;
	}
	return 0;
	//其他消息交给由系统提供的缺省处理函数
	return DefWindowProc(hwnd, message, wParam, lParam);
}

_DL_EXPORT int tipsWnd(char *in)
{
	//1.注册窗口类
	static TCHAR szAppName[] = TEXT ("HelloWin") ; //窗口类名称
	//定制"窗口类"结构

	//建立窗口
	HWND hwnd ;
	RECT rect;

	FindVimWindow();
	GetWindowRect(hwndText,&rect);
	int offset = AdjustPos(&rect,in);
	//top = rect.top;
	//left = rect.left;
	//建立窗口
	hwnd = CreateWindowEx(
			WS_EX_DLGMODALFRAME|WS_EX_TOOLWINDOW,//|WS_EX_TOPMOST,
			//szAppName,
			"#32770",
			TEXT("The Hello Program"),
			WS_POPUP|WS_DLGFRAME|WS_OVERLAPPED,
			0,
			0,
			400,
			300,
			m_vimHwnd,
			NULL,
			NULL,
			NULL);
	//sprintf(cBuffer,"%s","Hello \n world!\n涨九天在测试.--------------------\n^_^\n");
	snprintf(cBuffer,2048,"%s",in+offset);
	bufferSize = strlen(cBuffer);

	SetWindowLongPtr(hwnd,DWL_DLGPROC,(LPARAM)WndProc);

	ShowWindow (hwnd, SW_SHOW) ;
	UpdateWindow (hwnd) ;

	//消息循环
	MSG msg ;
	while (!stoped ) {
		if ( GetMessage(&msg,NULL,0,0)== 0 ) {
			break;
		}
		TranslateMessage (&msg) ; //转换消息
		DispatchMessage (&msg) ; //派发消息
	}
	/*
	while (GetMessage (&msg, NULL, 0, 0)) //从消息队列中取消息
	{
		TranslateMessage (&msg) ; //转换消息
		DispatchMessage (&msg) ; //派发消息
	}
	*/
	//UnregisterClass(szAppName,NULL);
	return strlen(in); ;
}
#ifndef DLL
//二、应用程序主函数
//参数:实例句柄、前一个实例的句柄、命令行参数、窗口显示方式
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance,
		PSTR szCmdLine, int iCmdShow)
{
	//1.注册窗口类
	static TCHAR szAppName[] = TEXT ("HelloWin") ; //窗口类名称
	//定制"窗口类"结构
	/*
	WNDCLASS wndclass ;
	wndclass.style = CS_HREDRAW | CS_VREDRAW ;
	wndclass.lpfnWndProc = WndProc ; //关联消息处理函数
	wndclass.cbClsExtra = 0 ;
	wndclass.cbWndExtra = 0 ;
	wndclass.hInstance = hInstance ; //实例句柄
	wndclass.hIcon = LoadIcon (NULL, IDI_APPLICATION) ; //图标
	wndclass.hCursor = LoadCursor (NULL, IDC_ARROW) ; //光标
	wndclass.hbrBackground = (HBRUSH) GetStockObject (WHITE_BRUSH); //画刷
	wndclass.lpszMenuName = NULL ;
	wndclass.lpszClassName = szAppName; //类名称
	//注册
	if (!RegisterClass (&wndclass))
	{
		MessageBox (NULL, TEXT ("RegisterClass Fail!"),
				szAppName, MB_ICONERROR) ;
		return 0 ;
	}
	*/

	//建立窗口
	HWND hwnd ;
	hwnd = CreateWindowEx(
			WS_EX_DLGMODALFRAME,
			//WS_EX_APPWINDOW,
			"#32770",
			//szAppName,
			TEXT("The Hello Program"),
			//WS_OVERLAPPEDWINDOW,
			WS_POPUP,
			0,
			0,
			400,
			300,
			NULL,
			NULL,
			NULL,
			NULL);

	top = 0;
	left =0;

	sprintf(cBuffer,"%s","Hellow\nWorld\n涨九天在测试.\nParameters:\n");
#ifndef DLL
	snprintf(cBuffer,2048,"%s",testdata);
#endif
	bufferSize = strlen(cBuffer);
	SetWindowLongPtr(hwnd,DWL_DLGPROC,(LPARAM)WndProc);

	ShowWindow (hwnd, iCmdShow) ;
	UpdateWindow (hwnd) ;

	//消息循环
	MSG msg ;
	while (!stoped ) {
		if ( GetMessage(&msg,NULL,0,0)== 0 ) {
			break;
		}
		TranslateMessage (&msg) ; //转换消息
		DispatchMessage (&msg) ; //派发消息
	}

	/*
	while (GetMessage (&msg, NULL, 0, 0) ) //从消息队列中取消息
	{
		TranslateMessage (&msg) ; //转换消息
		DispatchMessage (&msg) ; //派发消息
	}
	*/
	return 0 ;
}
#endif

// vim: ts=4:sw=4:sts=4
